
sudo: false
language: node_js

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm install -g grunt-cli

script:
  - pushd runner/qunit; npm install; ./node_modules/.bin/browserstack-runner --verbose; popd
  - pushd karma/karma-browserstack-example; npm install; npm test; popd
